# generated by datamodel-codegen:
#   filename:  dashboard_types_gen.json
#   timestamp: 2023-07-11T02:49:14+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel


class Model(BaseModel):
    __root__: Any
